AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - Gemfile
    - "**/*.gemfile"
    - bin/*
    - "*.gemspec"
    - lib/turbo_test_method_call_tracer_proxy/delegate_class.rb
    - test/unit/delegate_class_test.rb

Layout/LineLength:
  Enabled: true
  AutoCorrect: false
  Max: 100
  Exclude:
    - test/**/*

Metrics/AbcSize:
  Exclude:
    - test/helpers/*

Metrics/BlockLength:
  Exclude:
    - test/**/*_test.rb

Metrics/ClassLength:
  Exclude:
    - test/**/*
    - lib/tasks/*

Metrics/MethodLength:
  Max: 10
  Exclude:
    - test/**/*

Metrics/ModuleLength:
  Exclude:
    - test/**/*

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - test/unit/delegated_proxy/*
    - test/unit/internal_proxy/*
    - test/unit/ruby_behaviour/*

Style/OptionalBooleanParameter:
  Exclude:
    - test/**/*

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true


